[ids]

*

[main]

capslock = overload(control, esc)

rightalt = layer(num)

[num]

# Numbers
u = 7
i = 8
o = 9

j = 4
k = 5
l = 6

m = 1
, = 2
. = 3

n = 0

# Operators
a = /
s = *
d = -
f = +

# Other keys
g = =
h = backspace

# Decimal point
space = .

